language: python

sudo: false

os: linux
dist: trusty

matrix:
  include:
    - python: 3.6
      name: "python 3.6"

before_script:
  - python setup.py install
  - bash travis/enable-ssh-localhost.sh

script:
  - python -m pip install flake8 mypy pytest-cov codecov
  - flake8
  - python -m pytest
  - mkdir ~/remote_tmp_root
  - for run_file in tests/run_*.py ; do echo "$run_file"; python -m coverage run "$run_file";  done
  - coverage combine

after_success:
  - codecov