language: python

sudo: false

os: linux
dist: trusty

matrix:
  include:
    - python: 3.6
      name: "python 3.6"

before_script:
  - python setup.py install
  - bash travis/enable-ssh-localhost.sh

script:
  - python -m pip install flake8 mypy pytest-cov codecov
  - flake8
  - python -m pytest
  - for run_file in tests/run_*.py ; do python -m coverage run -a "$run_file" ;  done

after_success:
  - codecov